# Generated by Django 2.1.6 on 2019-03-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CounterpartyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='counterparty',
            name='counter_party_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counterparties.CounterpartyType'),
        ),
    ]
