# Generated by Django 2.1.6 on 2019-03-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_auto_20190304_1718'),
        ('counterparties', '0001_initial'),
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingmutationtype',
            options={'verbose_name': 'ING mutation type', 'verbose_name_plural': 'ING mutation types'},
        ),
    ]
