# Generated by Django 2.1.6 on 2019-03-10 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_auto_20190304_1718'),
        ('counterparties', '0001_initial'),
        ('import', '0002_auto_20190310_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=255)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank_accounts.BankAccount')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='counterparties.Counterparty')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contraaccount',
            unique_together={('description', 'bank_account_number')},
        ),
    ]
