# Generated by Django 2.1.6 on 2019-03-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iban_identifier', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_accounts.Bank')),
            ],
        ),
    ]
