# Generated by Django 2.1.6 on 2019-03-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_old_dutch',
        ),
    ]
