# Generated by Django 2.1.6 on 2019-03-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_remove_bankaccount_is_old_dutch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.Counterparty'),
        ),
    ]
